spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/pricing_engine_db
spring.datasource.username=heatblasteraa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080